version: '2'
services:

###############################
   cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199:7199

###############################
   cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
#
################################
#   cassandra2:
#    image: cassandra
#    container_name: cassandra2
#    ports:
#     - 9242:9042
#    links:
#     - cassandra0:seed
#    environment:
#     - CASSANDRA_SEEDS=seed